### ISSUE TITLE
Bug Report: One data source is missing.

### ISSUE THREAD

**Issue by JiaxiangBU** [rstudio/rstudio-conf#50]
Hi, @cwickham, the original one is in this issue https://github.com/hadley/neiss/issues/8. 
I just learn the tutorial, [Happy R Users Purrr by Charlotte Wickham](https://github.com/rstudio/rstudio-conf/tree/master/2017/Happy_R_Users_Purrr-Charlotte_Wickham) in this repository.
At page 58, there is a data file to be downloaded here, 

![image](https://user-images.githubusercontent.com/15884785/55369981-681a0080-552b-11e9-9c1e-d34cdba89e65.png)

But I don't find it in the package neiss. I ask @hadley  the author of this package, but he said, 

> I have no recollection of that data set, sorry.

![image](https://user-images.githubusercontent.com/15884785/55369915-20937480-552b-11e9-9a31-ce01113c3e30.png)

Would you like to tell me where I can get it?

**Comment by batpigandme** [comment]
The "From…" in this case references the original source of the data, not the source of the file itself, which is part of the tutorial — the whole directory for which can be found here ([`purrr_workshop.zip`](https://github.com/rstudio/rstudio-conf/blob/master/2017/Happy_R_Users_Purrr-Charlotte_Wickham/purrr_workshop.zip)):
https://github.com/rstudio/rstudio-conf/tree/master/2017/Happy_R_Users_Purrr-Charlotte_Wickham

Once you download and unzip that, the files for that workshop include:
data >> `neiss_by_day.rda`
![neiss by day](https://user-images.githubusercontent.com/831732/55417836-7245fa00-553f-11e9-8cf8-02d3562e8b02.png)
